# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('kode_booking', models.IntegerField(primary_key=True, serialize=False)),
                ('jumlah_penumpang', models.IntegerField()),
                ('waktu_mulai_booking', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Kereta',
            fields=[
                ('id_kereta', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kereta', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'kereta',
            },
        ),
        migrations.CreateModel(
            name='LayananKereta',
            fields=[
                ('id_layanan_kereta', models.IntegerField(primary_key=True, serialize=False)),
                ('kapasitas', models.IntegerField()),
                ('harga_tiket', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'layanan_kereta',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('kode_pembayaran', models.IntegerField(primary_key=True, serialize=False)),
                ('waktu_penagihan', models.DateTimeField()),
                ('waktu_pembayaran', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Penumpang',
            fields=[
                ('id_penumpang', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_identitas', models.CharField(max_length=24)),
                ('nama_penumpang', models.CharField(max_length=64)),
            ],
            options={
                'managed': False,
                'db_table': 'penumpang',
            },
        ),
        migrations.CreateModel(
            name='RangkaianPerjalanan',
            fields=[
                ('id_rangkaian_perjalanan', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_keberangkatan', models.DateTimeField()),
                ('waktu_kedatangan', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'rangkaian_perjalanan',
            },
        ),
        migrations.CreateModel(
            name='Stasiun',
            fields=[
                ('id_stasiun', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama_stasiun', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'stasiun',
            },
        ),
        migrations.CreateModel(
            name='TipePembayaran',
            fields=[
                ('id_tipe_pembayaran', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_tipe_pembayaran', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'tipe_pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Pemesan',
            fields=[
                ('booking', models.OneToOneField(db_column='kode_booking', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Booking')),
                ('nama_pemesan', models.CharField(max_length=64)),
                ('email_pemesan', models.CharField(max_length=64)),
                ('nomor_telepon_pemesan', models.CharField(max_length=16)),
                ('alamat_pemesan', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'pemesan',
            },
        ),
    ]
